### ISSUE TITLE
Credentials store error

### ISSUE THREAD

**Issue by man4ish** [EBIBioSamples/biosamples-v4#152]
I am trying to run 

> sudo docker-compose up

 and getting following error 

Pulling biosamples-agents-solr (biosamples:latest)...
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 952, in up
    start=not no_start
  File "/usr/lib/python2.7/dist-packages/compose/project.py", line 431, in up
    svc.ensure_image_exists(do_build=do_build)
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 312, in ensure_image_exists
    self.pull()
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 1029, in pull
    output = self.client.pull(repo, tag=tag, stream=True)
  File "/usr/lib/python2.7/dist-packages/docker/api/image.py", line 381, in pull
    header = auth.get_config_header(self, registry)
  File "/usr/lib/python2.7/dist-packages/docker/auth.py", line 50, in get_config_header
    authcfg = resolve_authconfig(client._auth_configs, registry)
  File "/usr/lib/python2.7/dist-packages/docker/auth.py", line 97, in resolve_authconfig
    authconfig, registry, store_name
  File "/usr/lib/python2.7/dist-packages/docker/auth.py", line 142, in _resolve_authconfig_credstore
    'Credentials store error: {0}'.format(repr(e))
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-secretservice exited with "Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached".',)

**Comment by theisuru** [comment]
Hi, Could you please add some info about your enviorenment eg. OS, docker, maven, Java version, ...

**Comment by theisuru** [comment]
Hope this is resolved.

**Comment by Luskan777** [comment]
Hello,
Probably the path of your docker-compose.yml file is wrong, in my case, in the context part I had put the path with Dokerfile at the end, in my example:
context: ./bin/web/Dockerfile.
I just needed to remove the Dockerfile, and it was "./bin/web/".
That's how I managed to solve
